-- Categories table
CREATE TABLE IF NOT EXISTS categories (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  naziv VARCHAR(255) NOT NULL,
  url_slug VARCHAR(255) NOT NULL UNIQUE,
  opis TEXT,
  slika_url VARCHAR(255),
  aktivan TINYINT(1) DEFAULT 1,
  kreirano_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  azurirano_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Products table (assuming similar structure, adjust as needed)
CREATE TABLE IF NOT EXISTS products (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  naziv VARCHAR(255) NOT NULL,
  url_slug VARCHAR(255) NOT NULL UNIQUE,
  opis TEXT,
  cena DECIMAL(10,2) NOT NULL,
  slika_url VARCHAR(255),
  kategorija_id INT(11),
  aktivan TINYINT(1) DEFAULT 1,
  kreirano_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  azurirano_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (kategorija_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Users table
CREATE TABLE IF NOT EXISTS users (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  role ENUM('user', 'admin') NOT NULL DEFAULT 'user'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;